defmodule RustQ.Config do
  @moduledoc """
  Small DSL for declaring RustQ-generated files in `rustq.exs`.

      import RustQ.Config

      rust_items :term_helpers, "native/generated_term_helpers.rs",
        items: RustQ.Rustler.term_helpers()
  """

  defmacro rustq(do: block) do
    quote do
      RustQ.Config.__start__()

      try do
        unquote(block)
        [generated: RustQ.Config.__finish__()]
      after
        RustQ.Config.__delete__()
      end
    end
  end

  defmacro generate(name, path, do: block) do
    quote do
      RustQ.Config.__start_target__(unquote(name), unquote(path))
      unquote(block)
      RustQ.Config.__finish_target__()
      RustQ.Config.__manifest__()
    end
  end

  defmacro generate(path, do: block) do
    quote do
      RustQ.Config.__start_target__(
        Path.basename(unquote(path), Path.extname(unquote(path))),
        unquote(path)
      )

      unquote(block)
      RustQ.Config.__finish_target__()
      RustQ.Config.__manifest__()
    end
  end

  defmacro rust_items(name, path, opts) do
    quote do
      RustQ.Config.__put_target__(
        unquote(name),
        unquote(path),
        build: fn -> RustQ.Config.__render_rust_items__(unquote(path), unquote(opts)) end
      )

      RustQ.Config.__manifest__()
    end
  end

  defmacro rust_items(path, opts) do
    quote do
      path = unquote(path)

      RustQ.Config.__put_target__(
        RustQ.Config.__target_name__(path),
        path,
        build: fn -> RustQ.Config.__render_rust_items__(path, unquote(opts)) end
      )

      RustQ.Config.__manifest__()
    end
  end

  defmacro render(template, opts \\ []) do
    quote do
      RustQ.Config.__put_target_option__(
        :build,
        fn -> RustQ.Config.__render__(unquote(template), unquote(opts)) end
      )
    end
  end

  defmacro build(fun) do
    quote do
      RustQ.Config.__put_target_option__(:build, unquote(fun))
    end
  end

  defmacro content(value) do
    quote do
      RustQ.Config.__put_target_option__(:content, unquote(value))
    end
  end

  def __start__, do: Process.put(:rustq_config_targets, [])
  def __delete__, do: Process.delete(:rustq_config_targets)

  def __finish__ do
    Process.get(:rustq_config_targets, [])
  end

  def __manifest__, do: [generated: Process.get(:rustq_config_targets, [])]

  def __start_target__(name, path) do
    __ensure_started__()
    Process.put(:rustq_config_target, {name, [path: path]})
  end

  def __put_target__(name, path, opts) do
    __ensure_started__()
    targets = Process.get(:rustq_config_targets, [])
    Process.put(:rustq_config_targets, [{name, Keyword.put(opts, :path, path)} | targets])
  end

  def __target_name__(path) do
    path
    |> Path.basename(Path.extname(path))
    |> String.replace_prefix("generated_", "")
  end

  def __ensure_started__ do
    unless Process.get(:rustq_config_targets) do
      __start__()
    end
  end

  def __put_target_option__(key, value) do
    {name, target} = Process.get(:rustq_config_target)
    Process.put(:rustq_config_target, {name, Keyword.put(target, key, value)})
  end

  def __finish_target__ do
    {name, target} = Process.delete(:rustq_config_target)
    targets = Process.get(:rustq_config_targets, [])
    Process.put(:rustq_config_targets, [{name, target} | targets])
    :ok
  end

  def __render_rust_items__(path, opts) do
    items = Keyword.fetch!(opts, :items)
    opts = Keyword.put(opts, :splice, items: items)

    __render__("__splice_items!();", Keyword.put(opts, :filename, Path.basename(path)))
  end

  def __render__(template, opts) do
    filename = Keyword.get(opts, :filename, "rustq_generated.rs")

    render_opts =
      opts
      |> Keyword.delete(:filename)
      |> expand_preamble()

    RustQ.render!(template, filename, render_opts)
  end

  defp expand_preamble(opts) do
    case Keyword.get(opts, :preamble, :rustq) do
      :rustq ->
        Keyword.put(
          opts,
          :preamble,
          "// This file is generated by RustQ. Do not edit by hand.\n\n"
        )

      _other ->
        opts
    end
  end
end
