defmodule RustQ.NativeCodegen do
  @moduledoc false

  alias RustQ.Rust.AST
  alias RustQ.Rust.AST.Builder, as: A
  alias RustQ.Rust.AST.Schema

  import RustQ.Rust.AST.ItemBuilder

  require A
  require RustQ.Rust.AST.ItemBuilder

  def generated_ast_support do
    [
      A.use("quote::quote"),
      A.use("rustler::{Atom, Env, NifResult, Term}"),
      A.use("syn::{Arm, Expr, Item, Pat, Stmt, Type}"),
      atoms_module(),
      ast_modules_module(),
      helper_items(),
      RustQ.NativeCodegen.Helpers.asts(),
      decode_ast_item_item(),
      decode_ast_type_item(),
      decode_ast_pat_item(),
      decode_ast_stmt_item(),
      decode_ast_expr_item(),
      decode_arm_helper_items(),
      RustQ.NativeCodegen.Decoders.asts(),
      decode_pat_helper_items(),
      decode_stmt_helper_items(),
      decode_expr_helper_items()
    ]
    |> List.flatten()
    |> AST.render_file_native()
    |> then(&"// This file is generated by RustQ. Do not edit by hand.\n\n#{&1}")
    |> format_rust()
  end

  defp atoms_module do
    A.module(
      :atoms,
      [
        A.macro_item("rustler::atoms! {\n    ok,\n    error,\n}")
      ],
      vis: :crate
    )
  end

  defp ast_modules_module do
    constants =
      Enum.map(Schema.nodes(), fn node ->
        A.const(node.rust_const, "&str", node.rust_module, vis: :crate)
      end)

    A.module(:ast_modules, constants, vis: :crate)
  end

  defp helper_items do
    [
      function :atom,
        vis: :crate,
        args: [env: "Env", name: "&str"],
        returns: "NifResult<Atom>" do
        A.return(A.path_call([:Atom, :from_str], [:env, :name]))
      end
    ]
  end

  defp decode_ast_item_item do
    function :decode_ast_item,
      vis: :crate,
      args: [term: "Term"],
      returns: "NifResult<Item>" do
      A.return do
        A.match A.method(A.try(A.call(:struct_name, [:term])), :as_str) do
          decode_ast_item_arms()
        end
      end
    end
  end

  defp decode_ast_item_arms do
    Schema.nodes(:item)
    |> Enum.map(&decode_ast_item_arm/1)
    |> Kernel.++([
      A.arm A.wildcard() do
        A.return(A.err(A.path([:rustler, :Error, :BadArg])))
      end
    ])
  end

  defp decode_ast_item_arm(%Schema.Node{name: :macro_item, rust_const: rust_const}) do
    A.arm A.path_pat([:ast_modules, rust_const]) do
      A.return(A.path_call([:super, :decode_ast_macro_item], [:term]))
    end
  end

  defp decode_ast_item_arm(%Schema.Node{name: name, rust_const: rust_const}) do
    {wrapper, decoder} = item_decoder(name)

    A.arm A.path_pat([:ast_modules, rust_const]) do
      A.return(
        A.ok(
          A.path_call([:Item, wrapper], [
            A.try(A.path_call([:super, decoder], [:term]))
          ])
        )
      )
    end
  end

  defp item_decoder(:use), do: {:Use, :decode_ast_use}
  defp item_decoder(:module), do: {:Mod, :decode_ast_module}
  defp item_decoder(:const), do: {:Const, :decode_ast_const}
  defp item_decoder(:function), do: {:Fn, :decode_ast_function}
  defp item_decoder(:struct), do: {:Struct, :decode_ast_struct}
  defp item_decoder(:enum), do: {:Enum, :decode_ast_enum}

  defp decode_ast_type_item do
    function :decode_ast_type,
      vis: :crate,
      args: [term: "Term"],
      returns: "NifResult<Type>" do
      A.return do
        A.match A.method(A.try(A.call(:struct_name, [:term])), :as_str) do
          decode_ast_type_arms()
        end
      end
    end
  end

  defp decode_ast_type_arms do
    Schema.nodes(:type)
    |> Enum.map(&decode_ast_type_arm/1)
    |> Kernel.++([
      A.arm A.wildcard() do
        A.return(A.err(A.path([:rustler, :Error, :BadArg])))
      end
    ])
  end

  defp decode_ast_type_arm(%Schema.Node{name: name, rust_const: rust_const}) do
    A.arm A.path_pat([:ast_modules, rust_const]) do
      A.return(A.path_call([:super, type_decoder(name)], [:term]))
    end
  end

  defp type_decoder(name), do: String.to_atom("decode_#{name}")

  defp decode_ast_pat_item do
    function :decode_ast_pat,
      vis: :crate,
      args: [term: "Term"],
      returns: "NifResult<Pat>" do
      A.return do
        A.match A.method(A.try(A.call(:struct_name, [:term])), :as_str) do
          decode_ast_pat_arms()
        end
      end
    end
  end

  defp decode_ast_pat_arms do
    Schema.nodes(:pat)
    |> Enum.map(&decode_ast_pat_arm/1)
    |> Kernel.++([
      A.arm A.wildcard() do
        A.return(A.err(A.path([:rustler, :Error, :BadArg])))
      end
    ])
  end

  defp decode_ast_pat_arm(%Schema.Node{name: name, rust_const: rust_const}) do
    A.arm A.path_pat([:ast_modules, rust_const]) do
      A.return(A.path_call(pat_decoder_path(name), [:term]))
    end
  end

  defp pat_decoder_path(:pat_atom_guard), do: [:super, :decode_pat_atom_guard]

  defp pat_decoder_path(name)
       when name in [
              :pat_var,
              :pat_wildcard,
              :pat_path,
              :pat_literal,
              :pat_none,
              :pat_some,
              :pat_tuple,
              :pat_ok,
              :pat_err,
              :pat_path_tuple,
              :pat_struct
            ],
       do: [pat_decoder(name)]

  defp pat_decoder_path(name),
    do: raise(ArgumentError, "missing pattern decoder for #{inspect(name)}")

  defp pat_decoder(name), do: String.to_atom("decode_#{name}")

  defp decode_ast_stmt_item do
    function :decode_ast_stmt,
      vis: :crate,
      args: [term: "Term"],
      returns: "NifResult<Stmt>" do
      A.return do
        A.match A.method(A.try(A.call(:struct_name, [:term])), :as_str) do
          decode_ast_stmt_arms()
        end
      end
    end
  end

  defp decode_ast_stmt_arms do
    Schema.nodes(:stmt)
    |> Enum.map(&decode_ast_stmt_arm/1)
    |> Kernel.++([
      A.arm A.wildcard() do
        A.return(A.err(A.path([:rustler, :Error, :BadArg])))
      end
    ])
  end

  defp decode_ast_stmt_arm(%Schema.Node{name: name, rust_const: rust_const}) do
    A.arm A.path_pat([:ast_modules, rust_const]) do
      A.return(A.path_call(stmt_decoder_path(name), [:term]))
    end
  end

  defp stmt_decoder_path(:let), do: [:decode_stmt_let]
  defp stmt_decoder_path(:expr_stmt), do: [:decode_stmt_expr_stmt]
  defp stmt_decoder_path(:return), do: [:decode_stmt_return]

  defp decode_ast_expr_item do
    function :decode_ast_expr,
      vis: :crate,
      args: [term: "Term"],
      returns: "NifResult<Expr>" do
      A.return do
        A.match A.method(A.try(A.call(:struct_name, [:term])), :as_str) do
          decode_ast_expr_arms()
        end
      end
    end
  end

  defp decode_ast_expr_arms do
    Schema.nodes(:expr)
    |> Enum.map(&decode_ast_expr_arm/1)
    |> Kernel.++([
      A.arm A.wildcard() do
        A.return(A.err(A.path([:rustler, :Error, :BadArg])))
      end
    ])
  end

  defp decode_ast_expr_arm(%Schema.Node{name: name, rust_const: rust_const}) do
    A.arm A.path_pat([:ast_modules, rust_const]) do
      A.return(A.path_call(expr_decoder_path(name), [:term]))
    end
  end

  defp expr_decoder_path(name)
       when name in [
              :var,
              :path,
              :field,
              :path_call,
              :method_call,
              :local_call,
              :struct_literal,
              :ref,
              :try,
              :tuple,
              :literal,
              :token_macro,
              :atom_value,
              :none,
              :some,
              :ok,
              :err,
              :nif_raise_atom,
              :match,
              :if,
              :binary_op
            ],
       do: [expr_decoder(name)]

  defp expr_decoder_path(name),
    do: raise(ArgumentError, "missing expression decoder for #{inspect(name)}")

  defp expr_decoder(name), do: String.to_atom("decode_expr_#{name}")

  defp decode_arm_helper_items do
    []
  end

  defp decode_pat_helper_items do
    []
  end

  defp decode_stmt_helper_items do
    []
  end

  defp decode_expr_helper_items do
    [
      function :decode_expr_ok,
        vis: :crate,
        args: [term: "Term"],
        returns: "NifResult<Expr>" do
        A.return do
          A.match A.try(A.path_call([:super, :optional_map_get], [:term, "expr"])) do
            A.arm A.some_pat(:expr_term) do
              A.return(
                A.if_expr(
                  A.try(A.path_call([:super, :is_nil], [:expr_term])),
                  [
                    A.return(
                      A.path_call([:super, :parse_expr_tokens], [A.token_macro(:quote, "Ok(())")])
                    )
                  ],
                  [
                    A.let(:expr, A.try(A.path_call([:super, :decode_expr], [:expr_term]))),
                    A.return(
                      A.path_call([:super, :parse_expr_tokens], [
                        A.token_macro(:quote, "Ok(#expr)")
                      ])
                    )
                  ]
                )
              )
            end

            A.arm A.none_pat() do
              A.return(
                A.path_call([:super, :parse_expr_tokens], [A.token_macro(:quote, "Ok(())")])
              )
            end
          end
        end
      end
    ]
  end

  defp format_rust(source) do
    path =
      Path.join(System.tmp_dir!(), "rustq_generated_#{System.unique_integer([:positive])}.rs")

    File.write!(path, source)

    try do
      case System.cmd("rustfmt", ["--edition", "2021", path], stderr_to_stdout: true) do
        {_output, 0} -> File.read!(path)
        {_output, _status} -> source
      end
    after
      File.rm(path)
    end
  rescue
    ErlangError -> source
  end
end
