defmodule RustQ.NativeCodegen do
  @moduledoc false

  @ast_modules [
    function: "Elixir.RustQ.Rust.AST.Function",
    struct: "Elixir.RustQ.Rust.AST.Struct",
    struct_field: "Elixir.RustQ.Rust.AST.StructField",
    enum: "Elixir.RustQ.Rust.AST.Enum",
    enum_variant: "Elixir.RustQ.Rust.AST.EnumVariant",
    let: "Elixir.RustQ.Rust.AST.Let",
    expr_stmt: "Elixir.RustQ.Rust.AST.ExprStmt",
    return: "Elixir.RustQ.Rust.AST.Return",
    var: "Elixir.RustQ.Rust.AST.Var",
    path: "Elixir.RustQ.Rust.AST.Path",
    field: "Elixir.RustQ.Rust.AST.Field",
    path_call: "Elixir.RustQ.Rust.AST.PathCall",
    method_call: "Elixir.RustQ.Rust.AST.MethodCall",
    local_call: "Elixir.RustQ.Rust.AST.LocalCall",
    struct_literal: "Elixir.RustQ.Rust.AST.StructLiteral",
    ref: "Elixir.RustQ.Rust.AST.Ref",
    try: "Elixir.RustQ.Rust.AST.Try",
    tuple: "Elixir.RustQ.Rust.AST.Tuple",
    literal: "Elixir.RustQ.Rust.AST.Literal",
    atom_value: "Elixir.RustQ.Rust.AST.AtomValue",
    none: "Elixir.RustQ.Rust.AST.None",
    some: "Elixir.RustQ.Rust.AST.Some",
    ok: "Elixir.RustQ.Rust.AST.Ok",
    err: "Elixir.RustQ.Rust.AST.Err",
    nif_raise_atom: "Elixir.RustQ.Rust.AST.NifRaiseAtom",
    match: "Elixir.RustQ.Rust.AST.Match",
    arm: "Elixir.RustQ.Rust.AST.Arm",
    pat_var: "Elixir.RustQ.Rust.AST.PatVar",
    pat_wildcard: "Elixir.RustQ.Rust.AST.PatWildcard",
    pat_literal: "Elixir.RustQ.Rust.AST.PatLiteral",
    pat_none: "Elixir.RustQ.Rust.AST.PatNone",
    pat_some: "Elixir.RustQ.Rust.AST.PatSome",
    pat_ok: "Elixir.RustQ.Rust.AST.PatOk",
    pat_err: "Elixir.RustQ.Rust.AST.PatErr",
    pat_path_tuple: "Elixir.RustQ.Rust.AST.PatPathTuple",
    pat_struct: "Elixir.RustQ.Rust.AST.PatStruct",
    pat_tuple: "Elixir.RustQ.Rust.AST.PatTuple",
    pat_atom_guard: "Elixir.RustQ.Rust.AST.PatAtomGuard",
    type_unit: "Elixir.RustQ.Rust.AST.TypeUnit",
    type_path: "Elixir.RustQ.Rust.AST.TypePath",
    type_ref: "Elixir.RustQ.Rust.AST.TypeRef",
    type_option: "Elixir.RustQ.Rust.AST.TypeOption",
    type_result: "Elixir.RustQ.Rust.AST.TypeResult",
    type_nif_result: "Elixir.RustQ.Rust.AST.TypeNifResult",
    type_vec: "Elixir.RustQ.Rust.AST.TypeVec"
  ]

  def generated_ast_support do
    constants =
      @ast_modules
      |> Enum.map_join("\n", fn {name, module} ->
        "    pub(crate) const #{constant_name(name)}: &str = #{inspect(module)};"
      end)

    """
    // This file is generated by RustQ. Do not edit by hand.

    use rustler::{Atom, Env, NifResult, Term};

    pub(crate) mod atoms {
        rustler::atoms! {
            ok,
            error,
        }
    }

    pub(crate) mod ast_modules {
    #{constants}
    }

    pub(crate) fn atom(env: Env, name: &str) -> NifResult<Atom> {
        Atom::from_str(env, name)
    }

    pub(crate) fn optional_map_get<'a>(term: Term<'a>, key: &str) -> NifResult<Option<Term<'a>>> {
        match term.map_get(atom(term.get_env(), key)?) {
            Ok(value) => Ok(Some(value)),
            Err(_) => Ok(None),
        }
    }

    pub(crate) fn atom_key(term: Term, key: &str) -> NifResult<String> {
        term.map_get(atom(term.get_env(), key)?)?.atom_to_string()
    }

    pub(crate) fn optional_atom_key(term: Term, key: &str) -> NifResult<Option<String>> {
        let value = term.map_get(atom(term.get_env(), key)?)?;
        if is_nil(value)? {
            Ok(None)
        } else {
            Ok(Some(value.atom_to_string()?))
        }
    }

    pub(crate) fn is_nil(term: Term) -> NifResult<bool> {
        Ok(term.is_atom() && term.atom_to_string()? == "nil")
    }

    pub(crate) fn struct_name(term: Term) -> NifResult<String> {
        term.map_get(atom(term.get_env(), "__struct__")?)?
            .atom_to_string()
    }

    pub(crate) fn expect_struct(term: Term, expected: &str) -> NifResult<()> {
        if struct_name(term)? == expected {
            Ok(())
        } else {
            Err(rustler::Error::BadArg)
        }
    }
    """
  end

  defp constant_name(name) do
    name
    |> Atom.to_string()
    |> String.upcase()
  end
end
