defmodule RustQ.NativeCodegen do
  @moduledoc false

  alias RustQ.Rust.AST
  alias RustQ.Rust.AST.Builder, as: A

  def generated_ast_support do
    [
      A.use([:quote, :quote]),
      A.use({[:rustler], [:Atom, :Env, :NifResult, :Term]}),
      A.use(
        {[:syn],
         [
           :Arm,
           :Expr,
           :Field,
           :FnArg,
           :Item,
           :ItemConst,
           :ItemEnum,
           :ItemFn,
           :ItemMod,
           :ItemStruct,
           :ItemStatic,
           :ItemUse,
           :Pat,
           :Path,
           :Stmt,
           :Type,
           :Variant
         ]}
      ),
      RustQ.NativeCodegen.Modules.asts(),
      RustQ.NativeCodegen.Helpers.asts(),
      RustQ.NativeCodegen.Dispatch.asts(),
      RustQ.NativeCodegen.Decoders.asts()
    ]
    |> List.flatten()
    |> AST.render_file_native()
    |> then(&"// This file is generated by RustQ. Do not edit by hand.\n\n#{&1}")
    |> format_rust()
  end

  defp format_rust(source) do
    path =
      Path.join(System.tmp_dir!(), "rustq_generated_#{System.unique_integer([:positive])}.rs")

    File.write!(path, source)

    try do
      case System.cmd("rustfmt", ["--edition", "2021", path], stderr_to_stdout: true) do
        {_output, 0} -> File.read!(path)
        {_output, _status} -> source
      end
    after
      File.rm(path)
    end
  rescue
    ErlangError -> source
  end
end
