defmodule RustQ.Test do
  @moduledoc """
  Composable ExUnit helpers for Rust generated by `defrust` and `defnif`.

  The helpers return source or boolean values so tests keep using ExUnit's
  ordinary `assert` macro, pattern matching, and diffs:

      defmodule MyApp.NativeTest do
        use RustQ.Test, async: true

        test "generates and exports the native boundary" do
          assert rust_source!(MyApp.Native, :sum_impl) =~ "fn sum_impl"
          assert nif_exported?(MyApp.Native, :sum, 1)
          assert RustQ.valid?(rust_source!(MyApp.Native), "my_app_native.rs")
        end
      end

  `rust_source!/1` returns a module's complete generated Rust.
  `rust_source!/2` renders one named generated function, which keeps source
  assertions focused and prevents matches across unrelated functions.
  """

  alias RustQ.Meta.AST, as: MetaAST
  alias RustQ.Rust
  alias RustQ.Rust.AST

  defmacro __using__(opts) do
    quote do
      use ExUnit.Case, unquote(opts)
      import RustQ.Test
    end
  end

  @doc "Returns a generated module's complete Rust source or raises."
  @spec rust_source!(module()) :: String.t()
  def rust_source!(module) when is_atom(module) do
    if Code.ensure_loaded?(module) and function_exported?(module, :__rustq_source__, 0) do
      module.__rustq_source__()
    else
      raise ArgumentError, "#{inspect(module)} does not expose __rustq_source__/0"
    end
  end

  @doc "Renders one named generated Rust function or raises."
  @spec rust_source!(module(), atom()) :: String.t()
  def rust_source!(module, function) when is_atom(module) and is_atom(function) do
    module
    |> MetaAST.function!(function)
    |> Rust.render()
  end

  @doc "Returns whether a function is exported to Elixir and marked as a Rustler NIF."
  @spec nif_exported?(module(), atom(), arity()) :: boolean()
  def nif_exported?(module, function, arity)
      when is_atom(module) and is_atom(function) and is_integer(arity) and arity >= 0 do
    Code.ensure_loaded?(module) and
      function_exported?(module, function, arity) and
      function_exported?(module, :__rustq_asts__, 0) and
      Enum.any?(MetaAST.functions(module), fn
        %AST.Function{name: ^function, attrs: attrs} ->
          Enum.any?(attrs, &match?(%AST.Attribute{path: [:rustler, :nif]}, &1))

        _item ->
          false
      end)
  end
end
