// This file is generated by RustQ. Do not edit by hand.

pub const ANSWER: u32 = 42;
mod atoms {
    rustler::atoms! {
        ok, value
    }
}
fn increment(value: u32) -> u32 {
    value + 1
}
fn increment_all(values: Vec<u32>) -> Vec<u32> {
    values.into_iter().map(increment).collect::<Vec<u32>>()
}
struct Input<'a> {
    value: Term<'a>,
}
fn decode_input<'a>(term: Term<'a>) -> NifResult<Input<'a>> {
    Ok(Input {
        value: term.map_get(atoms::value())?.decode::<Term<'a>>()?,
    })
}
