// This file is generated by RustQ. Do not edit by hand.

use quote::quote;

use rustler::{Atom, Env, NifResult, Term};

use syn::{Item, Pat, Type};

pub(crate) mod atoms {
    rustler::atoms! {
        ok, error,
    }
}

pub(crate) mod ast_modules {
    pub(crate) const USE: &str = "Elixir.RustQ.Rust.AST.Use";
    pub(crate) const MODULE: &str = "Elixir.RustQ.Rust.AST.Module";
    pub(crate) const CONST: &str = "Elixir.RustQ.Rust.AST.Const";
    pub(crate) const MACRO_ITEM: &str = "Elixir.RustQ.Rust.AST.MacroItem";
    pub(crate) const FUNCTION: &str = "Elixir.RustQ.Rust.AST.Function";
    pub(crate) const STRUCT: &str = "Elixir.RustQ.Rust.AST.Struct";
    pub(crate) const STRUCT_FIELD: &str = "Elixir.RustQ.Rust.AST.StructField";
    pub(crate) const ENUM: &str = "Elixir.RustQ.Rust.AST.Enum";
    pub(crate) const ENUM_VARIANT: &str = "Elixir.RustQ.Rust.AST.EnumVariant";
    pub(crate) const TYPE_PATH: &str = "Elixir.RustQ.Rust.AST.TypePath";
    pub(crate) const TYPE_REF: &str = "Elixir.RustQ.Rust.AST.TypeRef";
    pub(crate) const TYPE_OPTION: &str = "Elixir.RustQ.Rust.AST.TypeOption";
    pub(crate) const TYPE_RESULT: &str = "Elixir.RustQ.Rust.AST.TypeResult";
    pub(crate) const TYPE_NIF_RESULT: &str = "Elixir.RustQ.Rust.AST.TypeNifResult";
    pub(crate) const TYPE_VEC: &str = "Elixir.RustQ.Rust.AST.TypeVec";
    pub(crate) const TYPE_UNIT: &str = "Elixir.RustQ.Rust.AST.TypeUnit";
    pub(crate) const LET: &str = "Elixir.RustQ.Rust.AST.Let";
    pub(crate) const EXPR_STMT: &str = "Elixir.RustQ.Rust.AST.ExprStmt";
    pub(crate) const RETURN: &str = "Elixir.RustQ.Rust.AST.Return";
    pub(crate) const VAR: &str = "Elixir.RustQ.Rust.AST.Var";
    pub(crate) const PATH: &str = "Elixir.RustQ.Rust.AST.Path";
    pub(crate) const FIELD: &str = "Elixir.RustQ.Rust.AST.Field";
    pub(crate) const PATH_CALL: &str = "Elixir.RustQ.Rust.AST.PathCall";
    pub(crate) const METHOD_CALL: &str = "Elixir.RustQ.Rust.AST.MethodCall";
    pub(crate) const STRUCT_LITERAL: &str = "Elixir.RustQ.Rust.AST.StructLiteral";
    pub(crate) const LOCAL_CALL: &str = "Elixir.RustQ.Rust.AST.LocalCall";
    pub(crate) const REF: &str = "Elixir.RustQ.Rust.AST.Ref";
    pub(crate) const TRY: &str = "Elixir.RustQ.Rust.AST.Try";
    pub(crate) const TUPLE: &str = "Elixir.RustQ.Rust.AST.Tuple";
    pub(crate) const LITERAL: &str = "Elixir.RustQ.Rust.AST.Literal";
    pub(crate) const TOKEN_MACRO: &str = "Elixir.RustQ.Rust.AST.TokenMacro";
    pub(crate) const ATOM_VALUE: &str = "Elixir.RustQ.Rust.AST.AtomValue";
    pub(crate) const NONE: &str = "Elixir.RustQ.Rust.AST.None";
    pub(crate) const SOME: &str = "Elixir.RustQ.Rust.AST.Some";
    pub(crate) const OK: &str = "Elixir.RustQ.Rust.AST.Ok";
    pub(crate) const ERR: &str = "Elixir.RustQ.Rust.AST.Err";
    pub(crate) const NIF_RAISE_ATOM: &str = "Elixir.RustQ.Rust.AST.NifRaiseAtom";
    pub(crate) const MATCH: &str = "Elixir.RustQ.Rust.AST.Match";
    pub(crate) const IF: &str = "Elixir.RustQ.Rust.AST.If";
    pub(crate) const BINARY_OP: &str = "Elixir.RustQ.Rust.AST.BinaryOp";
    pub(crate) const ARM: &str = "Elixir.RustQ.Rust.AST.Arm";
    pub(crate) const PAT_VAR: &str = "Elixir.RustQ.Rust.AST.PatVar";
    pub(crate) const PAT_WILDCARD: &str = "Elixir.RustQ.Rust.AST.PatWildcard";
    pub(crate) const PAT_PATH: &str = "Elixir.RustQ.Rust.AST.PatPath";
    pub(crate) const PAT_LITERAL: &str = "Elixir.RustQ.Rust.AST.PatLiteral";
    pub(crate) const PAT_NONE: &str = "Elixir.RustQ.Rust.AST.PatNone";
    pub(crate) const PAT_SOME: &str = "Elixir.RustQ.Rust.AST.PatSome";
    pub(crate) const PAT_ATOM_GUARD: &str = "Elixir.RustQ.Rust.AST.PatAtomGuard";
    pub(crate) const PAT_TUPLE: &str = "Elixir.RustQ.Rust.AST.PatTuple";
    pub(crate) const PAT_OK: &str = "Elixir.RustQ.Rust.AST.PatOk";
    pub(crate) const PAT_ERR: &str = "Elixir.RustQ.Rust.AST.PatErr";
    pub(crate) const PAT_PATH_TUPLE: &str = "Elixir.RustQ.Rust.AST.PatPathTuple";
    pub(crate) const PAT_STRUCT: &str = "Elixir.RustQ.Rust.AST.PatStruct";
}

pub(crate) fn atom(env: Env, name: &str) -> NifResult<Atom> {
    Atom::from_str(env, name)
}

pub(crate) fn optional_map_get<'a>(term: Term<'a>, key: &str) -> NifResult<Option<Term<'a>>> {
    match term.map_get(atom(term.get_env(), key)?) {
        Ok(value) => Ok(Some(value)),
        Err(_) => Ok(None),
    }
}

pub(crate) fn atom_key(term: Term, key: &str) -> NifResult<String> {
    term.map_get(atom(term.get_env(), key)?)?.atom_to_string()
}

pub(crate) fn optional_atom_key(term: Term, key: &str) -> NifResult<Option<String>> {
    let value = term.map_get(atom(term.get_env(), key)?)?;
    if is_nil(value)? {
        Ok(None)
    } else {
        Ok(Some(value.atom_to_string()?))
    }
}

pub(crate) fn is_nil(term: Term) -> NifResult<bool> {
    Ok(term.is_atom() && term.atom_to_string()? == "nil")
}

pub(crate) fn struct_name(term: Term) -> NifResult<String> {
    term.map_get(atom(term.get_env(), "__struct__")?)?
        .atom_to_string()
}

pub(crate) fn expect_struct(term: Term, expected: &str) -> NifResult<()> {
    if struct_name(term)? == expected {
        Ok(())
    } else {
        Err(rustler::Error::BadArg)
    }
}

pub(crate) fn decode_ast_item(term: Term) -> NifResult<Item> {
    match struct_name(term)?.as_str() {
        ast_modules::USE => Ok(Item::Use(super::decode_ast_use(term)?)),
        ast_modules::MODULE => Ok(Item::Mod(super::decode_ast_module(term)?)),
        ast_modules::CONST => Ok(Item::Const(super::decode_ast_const(term)?)),
        ast_modules::MACRO_ITEM => super::decode_ast_macro_item(term),
        ast_modules::FUNCTION => Ok(Item::Fn(super::decode_ast_function(term)?)),
        ast_modules::STRUCT => Ok(Item::Struct(super::decode_ast_struct(term)?)),
        ast_modules::ENUM => Ok(Item::Enum(super::decode_ast_enum(term)?)),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_ast_type(term: Term) -> NifResult<Type> {
    match struct_name(term)?.as_str() {
        ast_modules::TYPE_PATH => super::decode_type_path(term),
        ast_modules::TYPE_REF => super::decode_type_ref(term),
        ast_modules::TYPE_OPTION => super::decode_type_option(term),
        ast_modules::TYPE_RESULT => super::decode_type_result(term),
        ast_modules::TYPE_NIF_RESULT => super::decode_type_nif_result(term),
        ast_modules::TYPE_VEC => super::decode_type_vec(term),
        ast_modules::TYPE_UNIT => super::decode_type_unit(term),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_ast_pat(term: Term) -> NifResult<Pat> {
    match struct_name(term)?.as_str() {
        ast_modules::PAT_VAR => decode_pat_var(term),
        ast_modules::PAT_WILDCARD => decode_pat_wildcard(term),
        ast_modules::PAT_PATH => decode_pat_path(term),
        ast_modules::PAT_LITERAL => decode_pat_literal(term),
        ast_modules::PAT_NONE => decode_pat_none(term),
        ast_modules::PAT_SOME => decode_pat_some(term),
        ast_modules::PAT_ATOM_GUARD => super::decode_pat_atom_guard(term),
        ast_modules::PAT_TUPLE => super::decode_pat_tuple(term),
        ast_modules::PAT_OK => decode_pat_ok(term),
        ast_modules::PAT_ERR => decode_pat_err(term),
        ast_modules::PAT_PATH_TUPLE => super::decode_pat_path_tuple(term),
        ast_modules::PAT_STRUCT => super::decode_pat_struct(term),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_pat_var(term: Term) -> NifResult<Pat> {
    let ident = quote::format_ident!("{}", super::atom_key(term, "name")?);
    super::parse_pat(quote!(# ident))
}

pub(crate) fn decode_pat_wildcard(_term: Term) -> NifResult<Pat> {
    super::parse_pat(quote!(_))
}

pub(crate) fn decode_pat_none(_term: Term) -> NifResult<Pat> {
    super::parse_pat(quote!(None))
}

pub(crate) fn decode_pat_path(term: Term) -> NifResult<Pat> {
    let path = super::parse_path(&super::path_parts(
        term.map_get(super::atom(term.get_env(), "path")?)?
            .map_get(super::atom(term.get_env(), "parts")?)?,
    )?)?;
    super::parse_pat(quote!(# path))
}

pub(crate) fn decode_pat_literal(term: Term) -> NifResult<Pat> {
    super::decode_pat_literal_value(term.map_get(super::atom(term.get_env(), "value")?)?)
}

pub(crate) fn decode_pat_some(term: Term) -> NifResult<Pat> {
    let pat = super::decode_pat(term.map_get(super::atom(term.get_env(), "pattern")?)?)?;
    super::parse_pat(quote!(Some(# pat)))
}

pub(crate) fn decode_pat_ok(term: Term) -> NifResult<Pat> {
    let pat = super::decode_pat(term.map_get(super::atom(term.get_env(), "pattern")?)?)?;
    super::parse_pat(quote!(Ok(# pat)))
}

pub(crate) fn decode_pat_err(term: Term) -> NifResult<Pat> {
    let pat = super::decode_pat(term.map_get(super::atom(term.get_env(), "pattern")?)?)?;
    super::parse_pat(quote!(Err(# pat)))
}
