// This file is generated by RustQ. Do not edit by hand.

use quote::quote;

use rustler::{Atom, Env, NifResult, Term};

use syn::{
    Arm, Expr, Field, FnArg, Item, ItemConst, ItemEnum, ItemFn, ItemMod, ItemStruct, ItemUse, Pat,
    Path, Stmt, Type, Variant,
};

pub(crate) mod atoms {
    rustler::atoms! {
        ok, error,
    }
}

pub(crate) mod ast_modules {
    pub(crate) const USE: &str = "Elixir.RustQ.Rust.AST.Use";
    pub(crate) const MODULE: &str = "Elixir.RustQ.Rust.AST.Module";
    pub(crate) const CONST: &str = "Elixir.RustQ.Rust.AST.Const";
    pub(crate) const MACRO_ITEM: &str = "Elixir.RustQ.Rust.AST.MacroItem";
    pub(crate) const FUNCTION: &str = "Elixir.RustQ.Rust.AST.Function";
    pub(crate) const STRUCT: &str = "Elixir.RustQ.Rust.AST.Struct";
    pub(crate) const ENUM: &str = "Elixir.RustQ.Rust.AST.Enum";
    pub(crate) const TYPE_PATH: &str = "Elixir.RustQ.Rust.AST.TypePath";
    pub(crate) const TYPE_REF: &str = "Elixir.RustQ.Rust.AST.TypeRef";
    pub(crate) const TYPE_OPTION: &str = "Elixir.RustQ.Rust.AST.TypeOption";
    pub(crate) const TYPE_RESULT: &str = "Elixir.RustQ.Rust.AST.TypeResult";
    pub(crate) const TYPE_NIF_RESULT: &str = "Elixir.RustQ.Rust.AST.TypeNifResult";
    pub(crate) const TYPE_VEC: &str = "Elixir.RustQ.Rust.AST.TypeVec";
    pub(crate) const TYPE_UNIT: &str = "Elixir.RustQ.Rust.AST.TypeUnit";
    pub(crate) const LET: &str = "Elixir.RustQ.Rust.AST.Let";
    pub(crate) const ASSIGN: &str = "Elixir.RustQ.Rust.AST.Assign";
    pub(crate) const EXPR_STMT: &str = "Elixir.RustQ.Rust.AST.ExprStmt";
    pub(crate) const RETURN: &str = "Elixir.RustQ.Rust.AST.Return";
    pub(crate) const EARLY_RETURN: &str = "Elixir.RustQ.Rust.AST.EarlyReturn";
    pub(crate) const VAR: &str = "Elixir.RustQ.Rust.AST.Var";
    pub(crate) const PATH: &str = "Elixir.RustQ.Rust.AST.Path";
    pub(crate) const FIELD: &str = "Elixir.RustQ.Rust.AST.Field";
    pub(crate) const PATH_CALL: &str = "Elixir.RustQ.Rust.AST.PathCall";
    pub(crate) const METHOD_CALL: &str = "Elixir.RustQ.Rust.AST.MethodCall";
    pub(crate) const STRUCT_LITERAL: &str = "Elixir.RustQ.Rust.AST.StructLiteral";
    pub(crate) const LOCAL_CALL: &str = "Elixir.RustQ.Rust.AST.LocalCall";
    pub(crate) const REF: &str = "Elixir.RustQ.Rust.AST.Ref";
    pub(crate) const TRY: &str = "Elixir.RustQ.Rust.AST.Try";
    pub(crate) const TUPLE: &str = "Elixir.RustQ.Rust.AST.Tuple";
    pub(crate) const VEC_LITERAL: &str = "Elixir.RustQ.Rust.AST.VecLiteral";
    pub(crate) const CLOSURE: &str = "Elixir.RustQ.Rust.AST.Closure";
    pub(crate) const LITERAL: &str = "Elixir.RustQ.Rust.AST.Literal";
    pub(crate) const TOKEN_MACRO: &str = "Elixir.RustQ.Rust.AST.TokenMacro";
    pub(crate) const MACRO_CALL: &str = "Elixir.RustQ.Rust.AST.MacroCall";
    pub(crate) const ATOM_VALUE: &str = "Elixir.RustQ.Rust.AST.AtomValue";
    pub(crate) const NONE: &str = "Elixir.RustQ.Rust.AST.None";
    pub(crate) const SOME: &str = "Elixir.RustQ.Rust.AST.Some";
    pub(crate) const OK: &str = "Elixir.RustQ.Rust.AST.Ok";
    pub(crate) const ERR: &str = "Elixir.RustQ.Rust.AST.Err";
    pub(crate) const NIF_RAISE_ATOM: &str = "Elixir.RustQ.Rust.AST.NifRaiseAtom";
    pub(crate) const MATCH: &str = "Elixir.RustQ.Rust.AST.Match";
    pub(crate) const IF: &str = "Elixir.RustQ.Rust.AST.If";
    pub(crate) const BINARY_OP: &str = "Elixir.RustQ.Rust.AST.BinaryOp";
    pub(crate) const PAT_VAR: &str = "Elixir.RustQ.Rust.AST.PatVar";
    pub(crate) const PAT_WILDCARD: &str = "Elixir.RustQ.Rust.AST.PatWildcard";
    pub(crate) const PAT_PATH: &str = "Elixir.RustQ.Rust.AST.PatPath";
    pub(crate) const PAT_LITERAL: &str = "Elixir.RustQ.Rust.AST.PatLiteral";
    pub(crate) const PAT_NONE: &str = "Elixir.RustQ.Rust.AST.PatNone";
    pub(crate) const PAT_SOME: &str = "Elixir.RustQ.Rust.AST.PatSome";
    pub(crate) const PAT_ATOM_GUARD: &str = "Elixir.RustQ.Rust.AST.PatAtomGuard";
    pub(crate) const PAT_TUPLE: &str = "Elixir.RustQ.Rust.AST.PatTuple";
    pub(crate) const PAT_OK: &str = "Elixir.RustQ.Rust.AST.PatOk";
    pub(crate) const PAT_ERR: &str = "Elixir.RustQ.Rust.AST.PatErr";
    pub(crate) const PAT_PATH_TUPLE: &str = "Elixir.RustQ.Rust.AST.PatPathTuple";
    pub(crate) const PAT_STRUCT: &str = "Elixir.RustQ.Rust.AST.PatStruct";
}

pub(crate) fn atom(env: Env, name: &str) -> NifResult<Atom> {
    Atom::from_str(env, name)
}

pub(crate) fn required_field<'a>(term: Term<'a>, key: &str) -> NifResult<Term<'a>> {
    term.map_get(atom(term.get_env(), key)?)
}

pub(crate) fn optional_map_get<'a>(term: Term<'a>, key: &str) -> NifResult<Option<Term<'a>>> {
    match term.map_get(atom(term.get_env(), key)?) {
        Ok(value) => Ok(Some(value)),
        Err(_reason) => Ok(None),
    }
}

pub(crate) fn atom_key<'a>(term: Term<'a>, key: &str) -> NifResult<String> {
    let value = term.map_get(atom(term.get_env(), key)?)?;
    value.atom_to_string()
}

pub(crate) fn optional_atom_key<'a>(term: Term<'a>, key: &str) -> NifResult<Option<String>> {
    let value = term.map_get(atom(term.get_env(), key)?)?;
    if is_nil(value)? {
        Ok(None)
    } else {
        Ok(Some(value.atom_to_string()?))
    }
}

pub(crate) fn is_nil<'a>(term: Term<'a>) -> NifResult<bool> {
    Ok(term.is_atom() && term.atom_to_string()? == "nil")
}

pub(crate) fn struct_name<'a>(term: Term<'a>) -> NifResult<String> {
    let value = term.map_get(atom(term.get_env(), "__struct__")?)?;
    value.atom_to_string()
}

pub(crate) fn expect_struct<'a>(term: Term<'a>, expected: &str) -> NifResult<()> {
    if struct_name(term)? == expected {
        Ok(())
    } else {
        Err(rustler::Error::BadArg)
    }
}

pub(crate) fn decode_ast_item(term: Term) -> NifResult<Item> {
    match struct_name(term)?.as_str() {
        ast_modules::USE => Ok(Item::Use(decode_ast_use(term)?)),
        ast_modules::MODULE => Ok(Item::Mod(decode_ast_module(term)?)),
        ast_modules::CONST => Ok(Item::Const(decode_ast_const(term)?)),
        ast_modules::MACRO_ITEM => decode_ast_macro_item(term),
        ast_modules::FUNCTION => Ok(Item::Fn(decode_ast_function(term)?)),
        ast_modules::STRUCT => Ok(Item::Struct(decode_ast_struct(term)?)),
        ast_modules::ENUM => Ok(Item::Enum(decode_ast_enum(term)?)),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_ast_type(term: Term) -> NifResult<Type> {
    match struct_name(term)?.as_str() {
        ast_modules::TYPE_PATH => decode_type_path(term),
        ast_modules::TYPE_REF => decode_type_ref(term),
        ast_modules::TYPE_OPTION => decode_type_option(term),
        ast_modules::TYPE_RESULT => decode_type_result(term),
        ast_modules::TYPE_NIF_RESULT => decode_type_nif_result(term),
        ast_modules::TYPE_VEC => decode_type_vec(term),
        ast_modules::TYPE_UNIT => decode_type_unit(term),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_ast_pat(term: Term) -> NifResult<Pat> {
    match struct_name(term)?.as_str() {
        ast_modules::PAT_VAR => decode_pat_var(term),
        ast_modules::PAT_WILDCARD => decode_pat_wildcard(term),
        ast_modules::PAT_PATH => decode_pat_path(term),
        ast_modules::PAT_LITERAL => decode_pat_literal(term),
        ast_modules::PAT_NONE => decode_pat_none(term),
        ast_modules::PAT_SOME => decode_pat_some(term),
        ast_modules::PAT_ATOM_GUARD => super::decode_pat_atom_guard(term),
        ast_modules::PAT_TUPLE => decode_pat_tuple(term),
        ast_modules::PAT_OK => decode_pat_ok(term),
        ast_modules::PAT_ERR => decode_pat_err(term),
        ast_modules::PAT_PATH_TUPLE => decode_pat_path_tuple(term),
        ast_modules::PAT_STRUCT => decode_pat_struct(term),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_ast_stmt(term: Term) -> NifResult<Stmt> {
    match struct_name(term)?.as_str() {
        ast_modules::LET => decode_stmt_let(term),
        ast_modules::ASSIGN => decode_stmt_assign(term),
        ast_modules::EXPR_STMT => decode_stmt_expr_stmt(term),
        ast_modules::RETURN => decode_stmt_return(term),
        ast_modules::EARLY_RETURN => decode_stmt_early_return(term),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_ast_expr(term: Term) -> NifResult<Expr> {
    match struct_name(term)?.as_str() {
        ast_modules::VAR => decode_expr_var(term),
        ast_modules::PATH => decode_expr_path(term),
        ast_modules::FIELD => decode_expr_field(term),
        ast_modules::PATH_CALL => decode_expr_path_call(term),
        ast_modules::METHOD_CALL => decode_expr_method_call(term),
        ast_modules::STRUCT_LITERAL => decode_expr_struct_literal(term),
        ast_modules::LOCAL_CALL => decode_expr_local_call(term),
        ast_modules::REF => decode_expr_ref(term),
        ast_modules::TRY => decode_expr_try(term),
        ast_modules::TUPLE => decode_expr_tuple(term),
        ast_modules::VEC_LITERAL => decode_expr_vec_literal(term),
        ast_modules::CLOSURE => decode_expr_closure(term),
        ast_modules::LITERAL => decode_expr_literal(term),
        ast_modules::TOKEN_MACRO => decode_expr_token_macro(term),
        ast_modules::MACRO_CALL => decode_expr_macro_call(term),
        ast_modules::ATOM_VALUE => decode_expr_atom_value(term),
        ast_modules::NONE => decode_expr_none(term),
        ast_modules::SOME => decode_expr_some(term),
        ast_modules::OK => decode_expr_ok(term),
        ast_modules::ERR => decode_expr_err(term),
        ast_modules::NIF_RAISE_ATOM => decode_expr_nif_raise_atom(term),
        ast_modules::MATCH => decode_expr_match(term),
        ast_modules::IF => decode_expr_if(term),
        ast_modules::BINARY_OP => decode_expr_binary_op(term),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_ast_use<'a>(term: Term<'a>) -> NifResult<ItemUse> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.Use")?;
    let parts = required_field(term, "parts")?;
    if is_nil(parts)? {
        let tree = super::string_field(term, "tree")?;
        super::parse_item_use(tree)
    } else {
        let parts = super::decode_string_list(parts)?;
        super::parse_item_use_path(parts)
    }
}

pub(crate) fn decode_ast_module<'a>(term: Term<'a>) -> NifResult<ItemMod> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.Module")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let vis = super::decode_vis(required_field(term, "vis")?)?;
    let items = super::decode_item_list(required_field(term, "items")?)?;
    super::parse_item_module(name, vis, items)
}

pub(crate) fn decode_ast_const<'a>(term: Term<'a>) -> NifResult<ItemConst> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.Const")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let ty = super::decode_type(required_field(term, "type")?)?;
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    let vis = super::decode_vis(required_field(term, "vis")?)?;
    super::parse_item_const(name, ty, expr, vis)
}

pub(crate) fn decode_ast_function<'a>(term: Term<'a>) -> NifResult<ItemFn> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.Function")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let vis = super::decode_vis(required_field(term, "vis")?)?;
    let args = super::decode_function_arg_list(required_field(term, "args")?)?;
    let returns = super::decode_type(required_field(term, "returns")?)?;
    let lifetime = optional_atom_key(term, "lifetime")?;
    let stmts = super::decode_stmt_list(required_field(term, "body")?)?;
    super::parse_item_function_args(name, vis, args, returns, lifetime, stmts)
}

pub(crate) fn decode_derive_path_list<'a>(term: Term<'a>) -> NifResult<Vec<Path>> {
    let terms = super::decode_derive_path_terms(term)?;
    terms
        .into_iter()
        .map(|derive_path| super::decode_path_value(derive_path))
        .collect()
}

pub(crate) fn decode_ast_struct<'a>(term: Term<'a>) -> NifResult<ItemStruct> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.Struct")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let vis = super::decode_vis(required_field(term, "vis")?)?;
    let derive = super::decode_derive(required_field(term, "derive")?)?;
    let lifetime = optional_atom_key(term, "lifetime")?;
    let fields = super::decode_struct_field_list(required_field(term, "fields")?)?;
    super::parse_item_struct(name, vis, derive, lifetime, fields)
}

pub(crate) fn decode_ast_macro_item<'a>(term: Term<'a>) -> NifResult<Item> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.MacroItem")?;
    let source = super::string_field(term, "source")?;
    super::parse_macro_item(source)
}

pub(crate) fn decode_ast_enum<'a>(term: Term<'a>) -> NifResult<ItemEnum> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.Enum")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let vis = super::decode_vis(required_field(term, "vis")?)?;
    let derive = super::decode_derive(required_field(term, "derive")?)?;
    let variants = super::decode_enum_variant_list(required_field(term, "variants")?)?;
    super::parse_item_enum(name, vis, derive, variants)
}

pub(crate) fn decode_function_arg<'a>(term: Term<'a>) -> NifResult<FnArg> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.FunctionArg")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let ty = super::decode_type(required_field(term, "type")?)?;
    super::parse_function_arg(name, ty)
}

pub(crate) fn decode_struct_field<'a>(term: Term<'a>) -> NifResult<Field> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.StructField")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let ty = super::decode_type(required_field(term, "type")?)?;
    let vis = super::decode_vis(required_field(term, "vis")?)?;
    super::parse_struct_field(name, ty, vis)
}

pub(crate) fn decode_enum_variant<'a>(term: Term<'a>) -> NifResult<Variant> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.EnumVariant")?;
    let name = super::format_ident_value(atom_key(term, "name")?);
    let tuple = super::decode_type_list(required_field(term, "tuple")?)?;
    super::parse_enum_variant(name, tuple)
}

pub(crate) fn path_parts<'a>(term: Term<'a>) -> NifResult<String> {
    let parts = super::decode_string_list(term)?;
    Ok(parts.join("::"))
}

pub(crate) fn decode_lifetime_list<'a>(term: Term<'a>) -> NifResult<Vec<String>> {
    super::decode_string_list(term)
}

pub(crate) fn decode_type_path<'a>(term: Term<'a>) -> NifResult<Type> {
    let parts = super::decode_string_list(required_field(term, "parts")?)?;
    let lifetimes = decode_lifetime_list(required_field(term, "lifetimes")?)?;
    let generics = super::decode_type_list(required_field(term, "generics")?)?;
    super::parse_type_path_with_generics(parts, lifetimes, generics)
}

pub(crate) fn decode_type_unit<'a>(_term: Term<'a>) -> NifResult<Type> {
    super::parse_type("()")
}

pub(crate) fn decode_type_ref<'a>(term: Term<'a>) -> NifResult<Type> {
    let inner = super::decode_type(required_field(term, "inner")?)?;
    let mutable = required_field(term, "mutable")?.decode()?;
    let lifetime = optional_atom_key(term, "lifetime")?;
    super::parse_type_ref(inner, mutable, lifetime)
}

pub(crate) fn decode_type_option<'a>(term: Term<'a>) -> NifResult<Type> {
    let inner = super::decode_type(required_field(term, "inner")?)?;
    super::parse_type_generic("Option", vec![inner])
}

pub(crate) fn decode_type_result<'a>(term: Term<'a>) -> NifResult<Type> {
    let ok = super::decode_type(required_field(term, "ok")?)?;
    let error = super::decode_type(required_field(term, "error")?)?;
    super::parse_type_generic("Result", vec![ok, error])
}

pub(crate) fn decode_type_nif_result<'a>(term: Term<'a>) -> NifResult<Type> {
    let inner = super::decode_type(required_field(term, "inner")?)?;
    super::parse_type_generic("NifResult", vec![inner])
}

pub(crate) fn decode_type_vec<'a>(term: Term<'a>) -> NifResult<Type> {
    let inner = super::decode_type(required_field(term, "inner")?)?;
    super::parse_type_generic("Vec", vec![inner])
}

pub(crate) fn decode_pat_var<'a>(term: Term<'a>) -> NifResult<Pat> {
    let ident = super::format_ident_value(atom_key(term, "name")?);
    super::parse_syn::<Pat>(quote!(# ident))
}

pub(crate) fn decode_pat_wildcard<'a>(_term: Term<'a>) -> NifResult<Pat> {
    super::parse_syn::<Pat>(quote!(_))
}

pub(crate) fn decode_pat_none<'a>(_term: Term<'a>) -> NifResult<Pat> {
    super::parse_syn::<Pat>(quote!(None))
}

pub(crate) fn decode_pat_path<'a>(term: Term<'a>) -> NifResult<Pat> {
    let path = super::parse_ast_path(required_field(term, "path")?)?;
    super::parse_syn::<Pat>(quote!(# path))
}

pub(crate) fn decode_pat_literal<'a>(term: Term<'a>) -> NifResult<Pat> {
    super::decode_pat_literal_value(required_field(term, "value")?)
}

pub(crate) fn decode_pat_some<'a>(term: Term<'a>) -> NifResult<Pat> {
    let pat = super::decode_pat(required_field(term, "pattern")?)?;
    super::parse_syn::<Pat>(quote!(Some(# pat)))
}

pub(crate) fn decode_pat_ok<'a>(term: Term<'a>) -> NifResult<Pat> {
    let pat = super::decode_pat(required_field(term, "pattern")?)?;
    super::parse_syn::<Pat>(quote!(Ok(# pat)))
}

pub(crate) fn decode_pat_err<'a>(term: Term<'a>) -> NifResult<Pat> {
    let pat = super::decode_pat(required_field(term, "pattern")?)?;
    super::parse_syn::<Pat>(quote!(Err(# pat)))
}

pub(crate) fn decode_pat_tuple<'a>(term: Term<'a>) -> NifResult<Pat> {
    let patterns = super::decode_pat_list(required_field(term, "patterns")?)?;
    super::parse_syn::<Pat>(quote!((# (# patterns),*)))
}

pub(crate) fn decode_pat_path_tuple<'a>(term: Term<'a>) -> NifResult<Pat> {
    let path = super::parse_ast_path(required_field(term, "path")?)?;
    let patterns = super::decode_pat_list(required_field(term, "patterns")?)?;
    super::parse_syn::<Pat>(quote!(# path(# (# patterns),*)))
}

pub(crate) fn decode_pat_struct<'a>(term: Term<'a>) -> NifResult<Pat> {
    let path = super::parse_ast_path(required_field(term, "path")?)?;
    let fields = super::decode_pat_struct_fields(required_field(term, "fields")?)?;
    super::parse_syn::<Pat>(quote!(# path { # (# fields),* }))
}

pub(crate) fn decode_stmt_assign<'a>(term: Term<'a>) -> NifResult<Stmt> {
    let target = super::decode_expr(required_field(term, "target")?)?;
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_assign_stmt(target, expr)
}

pub(crate) fn decode_stmt_expr_stmt<'a>(term: Term<'a>) -> NifResult<Stmt> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_syn::<Stmt>(quote!(# expr;))
}

pub(crate) fn decode_stmt_return<'a>(term: Term<'a>) -> NifResult<Stmt> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    Ok(Stmt::Expr(expr, None))
}

pub(crate) fn decode_stmt_early_return<'a>(term: Term<'a>) -> NifResult<Stmt> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_return_stmt(expr)
}

pub(crate) fn decode_stmt_let<'a>(term: Term<'a>) -> NifResult<Stmt> {
    let pattern = super::decode_pat(required_field(term, "pattern")?)?;
    let mutable = required_field(term, "mutable")?.decode()?;
    let pat_tokens = super::decode_let_pattern(pattern, mutable)?;
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    let ty = super::decode_optional_type_field(term, "type")?;
    super::parse_let_stmt(pat_tokens, ty, expr)
}

pub(crate) fn decode_arm<'a>(term: Term<'a>) -> NifResult<Arm> {
    expect_struct(term, "Elixir.RustQ.Rust.AST.Arm")?;
    let pat_term = required_field(term, "pattern")?;
    let block = super::decode_block(required_field(term, "body")?)?;
    if struct_name(pat_term)? == "Elixir.RustQ.Rust.AST.PatAtomGuard" {
        super::decode_atom_guard_arm(pat_term, block)
    } else {
        let pat = super::decode_pat(pat_term)?;
        super::parse_syn::<Arm>(quote!(# pat => # block,))
    }
}

pub(crate) fn decode_expr_var<'a>(term: Term<'a>) -> NifResult<Expr> {
    let ident = super::format_ident_value(atom_key(term, "name")?);
    super::parse_syn::<Expr>(quote!(# ident))
}

pub(crate) fn decode_expr_path<'a>(term: Term<'a>) -> NifResult<Expr> {
    let path = super::parse_ast_path(term)?;
    super::parse_path_expr(path)
}

pub(crate) fn decode_expr_atom_value<'a>(term: Term<'a>) -> NifResult<Expr> {
    let name = super::format_ident_value(atom_key(term, "name")?);
    super::parse_syn::<Expr>(quote!(atoms::# name()))
}

pub(crate) fn decode_expr_field<'a>(term: Term<'a>) -> NifResult<Expr> {
    let receiver = super::decode_expr(required_field(term, "receiver")?)?;
    let field = super::format_ident_value(atom_key(term, "field")?);
    super::parse_syn::<Expr>(quote!(# receiver.# field))
}

pub(crate) fn decode_expr_path_call<'a>(term: Term<'a>) -> NifResult<Expr> {
    let path = super::parse_ast_path(required_field(term, "path")?)?;
    let args = super::decode_expr_list(required_field(term, "args")?)?;
    super::parse_syn::<Expr>(quote!(# path(# (# args),*)))
}

pub(crate) fn decode_expr_method_call<'a>(term: Term<'a>) -> NifResult<Expr> {
    let receiver = super::decode_expr(required_field(term, "receiver")?)?;
    let method = super::format_ident_value(atom_key(term, "method")?);
    let args = super::decode_expr_list(required_field(term, "args")?)?;
    super::parse_syn::<Expr>(quote!(# receiver.# method(# (# args),*)))
}

pub(crate) fn decode_expr_local_call<'a>(term: Term<'a>) -> NifResult<Expr> {
    let name = atom_key(term, "name")?;
    let args = super::decode_expr_list(required_field(term, "args")?)?;
    super::parse_local_call(name, args)
}

pub(crate) fn decode_expr_ref<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    let mutable = required_field(term, "mutable")?.decode()?;
    if mutable {
        super::parse_syn::<Expr>(quote!(& mut # expr))
    } else {
        super::parse_syn::<Expr>(quote!(&# expr))
    }
}

pub(crate) fn decode_expr_struct_literal<'a>(term: Term<'a>) -> NifResult<Expr> {
    let path = super::decode_expr(required_field(term, "path")?)?;
    let fields = super::decode_struct_literal_fields(required_field(term, "fields")?)?;
    super::parse_syn::<Expr>(quote!(# path { # (# fields),* }))
}

pub(crate) fn decode_expr_nif_raise_atom<'a>(term: Term<'a>) -> NifResult<Expr> {
    let name = atom_key(term, "name")?;
    super::parse_syn::<Expr>(quote!(rustler::Error::RaiseAtom(# name)))
}

pub(crate) fn decode_expr_binary_op<'a>(term: Term<'a>) -> NifResult<Expr> {
    let left = super::decode_expr(required_field(term, "left")?)?;
    let right = super::decode_expr(required_field(term, "right")?)?;
    let op = atom_key(term, "op")?;
    match op.as_str() {
        "eq" => super::parse_syn::<Expr>(quote!(# left == # right)),
        "and" => super::parse_syn::<Expr>(quote!(# left && # right)),
        "or" => super::parse_syn::<Expr>(quote!(# left || # right)),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_expr_match<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    let arms = super::decode_arm_list(required_field(term, "arms")?)?;
    super::parse_syn::<Expr>(quote!(match # expr { # (# arms) * }))
}

pub(crate) fn decode_expr_if<'a>(term: Term<'a>) -> NifResult<Expr> {
    let condition = super::decode_expr(required_field(term, "condition")?)?;
    let then_block = super::decode_block(required_field(term, "then")?)?;
    let else_block = super::decode_block(required_field(term, "else")?)?;
    super::parse_syn::<Expr>(quote!(if # condition # then_block else # else_block))
}

pub(crate) fn decode_expr_tuple<'a>(term: Term<'a>) -> NifResult<Expr> {
    let values = super::decode_expr_list(required_field(term, "values")?)?;
    super::parse_syn::<Expr>(quote!((# (# values),*)))
}

pub(crate) fn decode_expr_vec_literal<'a>(term: Term<'a>) -> NifResult<Expr> {
    let values = super::decode_expr_list(required_field(term, "values")?)?;
    super::parse_syn::<Expr>(quote!(vec![# (# values),*]))
}

pub(crate) fn decode_expr_closure<'a>(term: Term<'a>) -> NifResult<Expr> {
    let args = super::decode_ident_list(required_field(term, "args")?)?;
    let body = super::decode_expr(required_field(term, "body")?)?;
    super::parse_syn::<Expr>(quote!(|# (# args),*| # body))
}

pub(crate) fn decode_expr_macro_call<'a>(term: Term<'a>) -> NifResult<Expr> {
    let path = super::parse_ast_path(required_field(term, "path")?)?;
    let args = super::decode_expr_list(required_field(term, "args")?)?;
    super::parse_syn::<Expr>(quote!(# path!(# (# args),*)))
}

pub(crate) fn decode_expr_token_macro<'a>(term: Term<'a>) -> NifResult<Expr> {
    let path = super::path_parts(required_field(required_field(term, "path")?, "parts")?)?;
    let tokens = super::string_field(term, "tokens")?;
    super::parse_expr(&format!("{}!({})", path, tokens))
}

pub(crate) fn decode_expr_ok<'a>(term: Term<'a>) -> NifResult<Expr> {
    let optional_expr = super::decode_optional_expr_field(term, "expr")?;
    match optional_expr {
        None => super::parse_syn::<Expr>(quote!(Ok(()))),
        Some(expr) => super::parse_syn::<Expr>(quote!(Ok(# expr))),
    }
}

pub(crate) fn decode_expr_none<'a>(_term: Term<'a>) -> NifResult<Expr> {
    super::parse_syn::<Expr>(quote!(None))
}

pub(crate) fn decode_expr_literal<'a>(term: Term<'a>) -> NifResult<Expr> {
    super::decode_literal_expr(required_field(term, "value")?)
}

pub(crate) fn decode_expr_try<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_syn::<Expr>(quote!(# expr ?))
}

pub(crate) fn decode_expr_some<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_syn::<Expr>(quote!(Some(# expr)))
}

pub(crate) fn decode_expr_err<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_syn::<Expr>(quote!(Err(# expr)))
}
