// This file is generated by RustQ. Do not edit by hand.

use quote::quote;

use rustler::{Atom, Env, NifResult, Term};

use syn::{Arm, Expr, Item, Pat, Stmt, Type};

pub(crate) mod atoms {
    rustler::atoms! {
        ok, error,
    }
}

pub(crate) mod ast_modules {
    pub(crate) const USE: &str = "Elixir.RustQ.Rust.AST.Use";
    pub(crate) const MODULE: &str = "Elixir.RustQ.Rust.AST.Module";
    pub(crate) const CONST: &str = "Elixir.RustQ.Rust.AST.Const";
    pub(crate) const MACRO_ITEM: &str = "Elixir.RustQ.Rust.AST.MacroItem";
    pub(crate) const FUNCTION: &str = "Elixir.RustQ.Rust.AST.Function";
    pub(crate) const STRUCT: &str = "Elixir.RustQ.Rust.AST.Struct";
    pub(crate) const STRUCT_FIELD: &str = "Elixir.RustQ.Rust.AST.StructField";
    pub(crate) const ENUM: &str = "Elixir.RustQ.Rust.AST.Enum";
    pub(crate) const ENUM_VARIANT: &str = "Elixir.RustQ.Rust.AST.EnumVariant";
    pub(crate) const TYPE_PATH: &str = "Elixir.RustQ.Rust.AST.TypePath";
    pub(crate) const TYPE_REF: &str = "Elixir.RustQ.Rust.AST.TypeRef";
    pub(crate) const TYPE_OPTION: &str = "Elixir.RustQ.Rust.AST.TypeOption";
    pub(crate) const TYPE_RESULT: &str = "Elixir.RustQ.Rust.AST.TypeResult";
    pub(crate) const TYPE_NIF_RESULT: &str = "Elixir.RustQ.Rust.AST.TypeNifResult";
    pub(crate) const TYPE_VEC: &str = "Elixir.RustQ.Rust.AST.TypeVec";
    pub(crate) const TYPE_UNIT: &str = "Elixir.RustQ.Rust.AST.TypeUnit";
    pub(crate) const LET: &str = "Elixir.RustQ.Rust.AST.Let";
    pub(crate) const EXPR_STMT: &str = "Elixir.RustQ.Rust.AST.ExprStmt";
    pub(crate) const RETURN: &str = "Elixir.RustQ.Rust.AST.Return";
    pub(crate) const VAR: &str = "Elixir.RustQ.Rust.AST.Var";
    pub(crate) const PATH: &str = "Elixir.RustQ.Rust.AST.Path";
    pub(crate) const FIELD: &str = "Elixir.RustQ.Rust.AST.Field";
    pub(crate) const PATH_CALL: &str = "Elixir.RustQ.Rust.AST.PathCall";
    pub(crate) const METHOD_CALL: &str = "Elixir.RustQ.Rust.AST.MethodCall";
    pub(crate) const STRUCT_LITERAL: &str = "Elixir.RustQ.Rust.AST.StructLiteral";
    pub(crate) const LOCAL_CALL: &str = "Elixir.RustQ.Rust.AST.LocalCall";
    pub(crate) const REF: &str = "Elixir.RustQ.Rust.AST.Ref";
    pub(crate) const TRY: &str = "Elixir.RustQ.Rust.AST.Try";
    pub(crate) const TUPLE: &str = "Elixir.RustQ.Rust.AST.Tuple";
    pub(crate) const LITERAL: &str = "Elixir.RustQ.Rust.AST.Literal";
    pub(crate) const TOKEN_MACRO: &str = "Elixir.RustQ.Rust.AST.TokenMacro";
    pub(crate) const ATOM_VALUE: &str = "Elixir.RustQ.Rust.AST.AtomValue";
    pub(crate) const NONE: &str = "Elixir.RustQ.Rust.AST.None";
    pub(crate) const SOME: &str = "Elixir.RustQ.Rust.AST.Some";
    pub(crate) const OK: &str = "Elixir.RustQ.Rust.AST.Ok";
    pub(crate) const ERR: &str = "Elixir.RustQ.Rust.AST.Err";
    pub(crate) const NIF_RAISE_ATOM: &str = "Elixir.RustQ.Rust.AST.NifRaiseAtom";
    pub(crate) const MATCH: &str = "Elixir.RustQ.Rust.AST.Match";
    pub(crate) const IF: &str = "Elixir.RustQ.Rust.AST.If";
    pub(crate) const BINARY_OP: &str = "Elixir.RustQ.Rust.AST.BinaryOp";
    pub(crate) const ARM: &str = "Elixir.RustQ.Rust.AST.Arm";
    pub(crate) const PAT_VAR: &str = "Elixir.RustQ.Rust.AST.PatVar";
    pub(crate) const PAT_WILDCARD: &str = "Elixir.RustQ.Rust.AST.PatWildcard";
    pub(crate) const PAT_PATH: &str = "Elixir.RustQ.Rust.AST.PatPath";
    pub(crate) const PAT_LITERAL: &str = "Elixir.RustQ.Rust.AST.PatLiteral";
    pub(crate) const PAT_NONE: &str = "Elixir.RustQ.Rust.AST.PatNone";
    pub(crate) const PAT_SOME: &str = "Elixir.RustQ.Rust.AST.PatSome";
    pub(crate) const PAT_ATOM_GUARD: &str = "Elixir.RustQ.Rust.AST.PatAtomGuard";
    pub(crate) const PAT_TUPLE: &str = "Elixir.RustQ.Rust.AST.PatTuple";
    pub(crate) const PAT_OK: &str = "Elixir.RustQ.Rust.AST.PatOk";
    pub(crate) const PAT_ERR: &str = "Elixir.RustQ.Rust.AST.PatErr";
    pub(crate) const PAT_PATH_TUPLE: &str = "Elixir.RustQ.Rust.AST.PatPathTuple";
    pub(crate) const PAT_STRUCT: &str = "Elixir.RustQ.Rust.AST.PatStruct";
}

pub(crate) fn atom(env: Env, name: &str) -> NifResult<Atom> {
    Atom::from_str(env, name)
}

pub(crate) fn required_field<'a>(term: Term<'a>, key: &str) -> NifResult<Term<'a>> {
    term.map_get(atom(term.get_env(), key)?)
}

pub(crate) fn optional_map_get<'a>(term: Term<'a>, key: &str) -> NifResult<Option<Term<'a>>> {
    match term.map_get(atom(term.get_env(), key)?) {
        Ok(value) => Ok(Some(value)),
        Err(_reason) => Ok(None),
    }
}

pub(crate) fn atom_key<'a>(term: Term<'a>, key: &str) -> NifResult<String> {
    let value = term.map_get(atom(term.get_env(), key)?)?;
    value.atom_to_string()
}

pub(crate) fn optional_atom_key<'a>(term: Term<'a>, key: &str) -> NifResult<Option<String>> {
    let value = term.map_get(atom(term.get_env(), key)?)?;
    if is_nil(value)? {
        Ok(None)
    } else {
        Ok(Some(value.atom_to_string()?))
    }
}

pub(crate) fn is_nil<'a>(term: Term<'a>) -> NifResult<bool> {
    Ok(term.is_atom() && term.atom_to_string()? == "nil")
}

pub(crate) fn struct_name<'a>(term: Term<'a>) -> NifResult<String> {
    let value = term.map_get(atom(term.get_env(), "__struct__")?)?;
    value.atom_to_string()
}

pub(crate) fn expect_struct<'a>(term: Term<'a>, expected: &str) -> NifResult<()> {
    if struct_name(term)? == expected {
        Ok(())
    } else {
        Err(rustler::Error::BadArg)
    }
}

pub(crate) fn decode_ast_item(term: Term) -> NifResult<Item> {
    match struct_name(term)?.as_str() {
        ast_modules::USE => Ok(Item::Use(super::decode_ast_use(term)?)),
        ast_modules::MODULE => Ok(Item::Mod(super::decode_ast_module(term)?)),
        ast_modules::CONST => Ok(Item::Const(super::decode_ast_const(term)?)),
        ast_modules::MACRO_ITEM => super::decode_ast_macro_item(term),
        ast_modules::FUNCTION => Ok(Item::Fn(super::decode_ast_function(term)?)),
        ast_modules::STRUCT => Ok(Item::Struct(super::decode_ast_struct(term)?)),
        ast_modules::ENUM => Ok(Item::Enum(super::decode_ast_enum(term)?)),
        _ => Err(rustler::Error::BadArg),
    }
}
pub(crate) fn decode_ast_type(term: Term) -> NifResult<Type> {
    match struct_name(term)?.as_str() {
        ast_modules::TYPE_PATH => super::decode_type_path(term),
        ast_modules::TYPE_REF => super::decode_type_ref(term),
        ast_modules::TYPE_OPTION => super::decode_type_option(term),
        ast_modules::TYPE_RESULT => super::decode_type_result(term),
        ast_modules::TYPE_NIF_RESULT => super::decode_type_nif_result(term),
        ast_modules::TYPE_VEC => super::decode_type_vec(term),
        ast_modules::TYPE_UNIT => super::decode_type_unit(term),
        _ => Err(rustler::Error::BadArg),
    }
}
pub(crate) fn decode_ast_pat(term: Term) -> NifResult<Pat> {
    match struct_name(term)?.as_str() {
        ast_modules::PAT_VAR => decode_pat_var(term),
        ast_modules::PAT_WILDCARD => decode_pat_wildcard(term),
        ast_modules::PAT_PATH => decode_pat_path(term),
        ast_modules::PAT_LITERAL => decode_pat_literal(term),
        ast_modules::PAT_NONE => decode_pat_none(term),
        ast_modules::PAT_SOME => decode_pat_some(term),
        ast_modules::PAT_ATOM_GUARD => super::decode_pat_atom_guard(term),
        ast_modules::PAT_TUPLE => decode_pat_tuple(term),
        ast_modules::PAT_OK => decode_pat_ok(term),
        ast_modules::PAT_ERR => decode_pat_err(term),
        ast_modules::PAT_PATH_TUPLE => decode_pat_path_tuple(term),
        ast_modules::PAT_STRUCT => decode_pat_struct(term),
        _ => Err(rustler::Error::BadArg),
    }
}
pub(crate) fn decode_ast_stmt(term: Term) -> NifResult<Stmt> {
    match struct_name(term)?.as_str() {
        ast_modules::LET => decode_stmt_let(term),
        ast_modules::EXPR_STMT => decode_stmt_expr_stmt(term),
        ast_modules::RETURN => decode_stmt_return(term),
        _ => Err(rustler::Error::BadArg),
    }
}
pub(crate) fn decode_ast_expr(term: Term) -> NifResult<Expr> {
    match struct_name(term)?.as_str() {
        ast_modules::VAR => decode_expr_var(term),
        ast_modules::PATH => decode_expr_path(term),
        ast_modules::FIELD => decode_expr_field(term),
        ast_modules::PATH_CALL => decode_expr_path_call(term),
        ast_modules::METHOD_CALL => decode_expr_method_call(term),
        ast_modules::STRUCT_LITERAL => decode_expr_struct_literal(term),
        ast_modules::LOCAL_CALL => decode_expr_local_call(term),
        ast_modules::REF => decode_expr_ref(term),
        ast_modules::TRY => decode_expr_try(term),
        ast_modules::TUPLE => decode_expr_tuple(term),
        ast_modules::LITERAL => decode_expr_literal(term),
        ast_modules::TOKEN_MACRO => decode_expr_token_macro(term),
        ast_modules::ATOM_VALUE => decode_expr_atom_value(term),
        ast_modules::NONE => decode_expr_none(term),
        ast_modules::SOME => decode_expr_some(term),
        ast_modules::OK => decode_expr_ok(term),
        ast_modules::ERR => decode_expr_err(term),
        ast_modules::NIF_RAISE_ATOM => decode_expr_nif_raise_atom(term),
        ast_modules::MATCH => decode_expr_match(term),
        ast_modules::IF => decode_expr_if(term),
        ast_modules::BINARY_OP => decode_expr_binary_op(term),
        _ => Err(rustler::Error::BadArg),
    }
}
pub(crate) fn decode_arm(term: Term) -> NifResult<Arm> {
    super::expect_struct(term, ast_modules::ARM)?;
    let pat_term = term.map_get(super::atom(term.get_env(), "pattern")?)?;
    let block = super::decode_block(term.map_get(super::atom(term.get_env(), "body")?)?)?;
    match super::struct_name(pat_term)?.as_str() {
        ast_modules::PAT_ATOM_GUARD => super::decode_atom_guard_arm(pat_term, block),
        _ => {
            let pat = super::decode_pat(pat_term)?;
            super::parse_arm(quote!(#pat => #block,))
        }
    }
}
pub(crate) fn decode_pat_var<'a>(term: Term<'a>) -> NifResult<Pat> {
    let ident = super::format_ident_value(atom_key(term, "name")?);
    super::parse_pat(quote!(# ident))
}

pub(crate) fn decode_pat_wildcard<'a>(_term: Term<'a>) -> NifResult<Pat> {
    super::parse_pat(quote!(_))
}

pub(crate) fn decode_pat_none<'a>(_term: Term<'a>) -> NifResult<Pat> {
    super::parse_pat(quote!(None))
}

pub(crate) fn decode_pat_path<'a>(term: Term<'a>) -> NifResult<Pat> {
    let parts = super::path_parts(required_field(term, "parts")?)?;
    let path = super::parse_path(&parts)?;
    super::parse_pat(quote!(# path))
}

pub(crate) fn decode_pat_literal<'a>(term: Term<'a>) -> NifResult<Pat> {
    super::decode_pat_literal_value(required_field(term, "value")?)
}

pub(crate) fn decode_pat_some<'a>(term: Term<'a>) -> NifResult<Pat> {
    let pat = super::decode_pat(required_field(term, "pattern")?)?;
    super::parse_pat(quote!(Some(# pat)))
}

pub(crate) fn decode_pat_ok<'a>(term: Term<'a>) -> NifResult<Pat> {
    let pat = super::decode_pat(required_field(term, "pattern")?)?;
    super::parse_pat(quote!(Ok(# pat)))
}

pub(crate) fn decode_pat_err<'a>(term: Term<'a>) -> NifResult<Pat> {
    let pat = super::decode_pat(required_field(term, "pattern")?)?;
    super::parse_pat(quote!(Err(# pat)))
}

pub(crate) fn decode_stmt_expr_stmt<'a>(term: Term<'a>) -> NifResult<Stmt> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_stmt(quote!(# expr;))
}

pub(crate) fn decode_stmt_return<'a>(term: Term<'a>) -> NifResult<Stmt> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    Ok(Stmt::Expr(expr, None))
}

pub(crate) fn decode_expr_var<'a>(term: Term<'a>) -> NifResult<Expr> {
    let ident = super::format_ident_value(atom_key(term, "name")?);
    super::parse_expr_tokens(quote!(# ident))
}

pub(crate) fn decode_expr_path<'a>(term: Term<'a>) -> NifResult<Expr> {
    let parts = super::path_parts(required_field(term, "parts")?)?;
    super::parse_expr(&parts)
}

pub(crate) fn decode_expr_atom_value<'a>(term: Term<'a>) -> NifResult<Expr> {
    let name = super::format_ident_value(atom_key(term, "name")?);
    super::parse_expr_tokens(quote!(atoms::# name()))
}

pub(crate) fn decode_expr_field<'a>(term: Term<'a>) -> NifResult<Expr> {
    let receiver = super::decode_expr(required_field(term, "receiver")?)?;
    let field = super::format_ident_value(atom_key(term, "field")?);
    super::parse_expr_tokens(quote!(# receiver.# field))
}

pub(crate) fn decode_expr_path_call<'a>(term: Term<'a>) -> NifResult<Expr> {
    let path = super::parse_ast_path(required_field(term, "path")?)?;
    let args = super::decode_expr_list(required_field(term, "args")?)?;
    super::parse_expr_tokens(quote!(# path(# (# args),*)))
}

pub(crate) fn decode_expr_method_call<'a>(term: Term<'a>) -> NifResult<Expr> {
    let receiver = super::decode_expr(required_field(term, "receiver")?)?;
    let method = super::format_ident_value(atom_key(term, "method")?);
    let args = super::decode_expr_list(required_field(term, "args")?)?;
    super::parse_expr_tokens(quote!(# receiver.# method(# (# args),*)))
}

pub(crate) fn decode_expr_local_call<'a>(term: Term<'a>) -> NifResult<Expr> {
    let name = atom_key(term, "name")?;
    let args = super::decode_expr_list(required_field(term, "args")?)?;
    super::parse_local_call(name, args)
}

pub(crate) fn decode_expr_ref<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    let mutable = required_field(term, "mutable")?.decode()?;
    if mutable {
        super::parse_expr_tokens(quote!(& mut # expr))
    } else {
        super::parse_expr_tokens(quote!(&# expr))
    }
}

pub(crate) fn decode_expr_none<'a>(_term: Term<'a>) -> NifResult<Expr> {
    super::parse_expr_tokens(quote!(None))
}

pub(crate) fn decode_expr_literal<'a>(term: Term<'a>) -> NifResult<Expr> {
    super::decode_literal_expr(required_field(term, "value")?)
}

pub(crate) fn decode_expr_try<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_expr_tokens(quote!(# expr ?))
}

pub(crate) fn decode_expr_some<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_expr_tokens(quote!(Some(# expr)))
}

pub(crate) fn decode_expr_err<'a>(term: Term<'a>) -> NifResult<Expr> {
    let expr = super::decode_expr(required_field(term, "expr")?)?;
    super::parse_expr_tokens(quote!(Err(# expr)))
}

pub(crate) fn decode_pat_tuple(term: Term) -> NifResult<Pat> {
    let patterns = super::decode_pat_list(term.map_get(super::atom(term.get_env(), "patterns")?)?)?;
    super::parse_pat(quote!((# (# patterns),*)))
}

pub(crate) fn decode_pat_path_tuple(term: Term) -> NifResult<Pat> {
    let path = super::parse_path(&super::path_parts(
        term.map_get(super::atom(term.get_env(), "path")?)?
            .map_get(super::atom(term.get_env(), "parts")?)?,
    )?)?;
    let patterns = super::decode_pat_list(term.map_get(super::atom(term.get_env(), "patterns")?)?)?;
    super::parse_pat(quote!(# path(# (# patterns),*)))
}

pub(crate) fn decode_pat_struct(term: Term) -> NifResult<Pat> {
    let path = super::parse_path(&super::path_parts(
        term.map_get(super::atom(term.get_env(), "path")?)?
            .map_get(super::atom(term.get_env(), "parts")?)?,
    )?)?;
    let fields =
        super::decode_pat_struct_fields(term.map_get(super::atom(term.get_env(), "fields")?)?)?;
    super::parse_pat(quote!(# path { # (# fields),* }))
}

pub(crate) fn decode_stmt_let(term: Term) -> NifResult<Stmt> {
    let pattern = super::decode_pat(term.map_get(super::atom(term.get_env(), "pattern")?)?)?;
    let mutable = term
        .map_get(super::atom(term.get_env(), "mutable")?)?
        .decode()?;
    let pat_tokens = super::decode_let_pattern(pattern, mutable)?;
    let expr = super::decode_expr(term.map_get(super::atom(term.get_env(), "expr")?)?)?;
    let ty = match super::optional_map_get(term, "type")? {
        Some(type_term) => {
            if super::is_nil(type_term)? {
                None
            } else {
                let ty = super::decode_type(type_term)?;
                Some(ty)
            }
        }
        None => None,
    };
    super::parse_let_stmt(pat_tokens, ty, expr)
}

pub(crate) fn decode_expr_token_macro(term: Term) -> NifResult<Expr> {
    let path = super::path_parts(
        term.map_get(super::atom(term.get_env(), "path")?)?
            .map_get(super::atom(term.get_env(), "parts")?)?,
    )?;
    let tokens: String = term
        .map_get(super::atom(term.get_env(), "tokens")?)?
        .decode()?;
    super::parse_expr(&format!("{}!({})", path, tokens))
}

pub(crate) fn decode_expr_struct_literal(term: Term) -> NifResult<Expr> {
    let path = super::decode_expr(term.map_get(super::atom(term.get_env(), "path")?)?)?;
    let fields =
        super::decode_struct_literal_fields(term.map_get(super::atom(term.get_env(), "fields")?)?)?;
    super::parse_expr_tokens(quote!(# path { # (# fields),* }))
}

pub(crate) fn decode_expr_ok(term: Term) -> NifResult<Expr> {
    match super::optional_map_get(term, "expr")? {
        Some(expr_term) => {
            if super::is_nil(expr_term)? {
                super::parse_expr_tokens(quote!(Ok(())))
            } else {
                let expr = super::decode_expr(expr_term)?;
                super::parse_expr_tokens(quote!(Ok(# expr)))
            }
        }
        None => super::parse_expr_tokens(quote!(Ok(()))),
    }
}

pub(crate) fn decode_expr_nif_raise_atom(term: Term) -> NifResult<Expr> {
    let name = super::atom_key(term, "name")?;
    super::parse_expr_tokens(quote!(rustler::Error::RaiseAtom(# name)))
}

pub(crate) fn decode_expr_binary_op(term: Term) -> NifResult<Expr> {
    let left = super::decode_expr(term.map_get(super::atom(term.get_env(), "left")?)?)?;
    let right = super::decode_expr(term.map_get(super::atom(term.get_env(), "right")?)?)?;
    let op = super::atom_key(term, "op")?;
    match op.as_str() {
        "eq" => super::parse_expr_tokens(quote!(# left == # right)),
        "and" => super::parse_expr_tokens(quote!(# left && # right)),
        "or" => super::parse_expr_tokens(quote!(# left || # right)),
        _ => Err(rustler::Error::BadArg),
    }
}

pub(crate) fn decode_expr_match(term: Term) -> NifResult<Expr> {
    let expr = super::decode_expr(term.map_get(super::atom(term.get_env(), "expr")?)?)?;
    let arms = super::decode_arm_list(term.map_get(super::atom(term.get_env(), "arms")?)?)?;
    super::parse_expr_tokens(quote!(match # expr { # (# arms) * }))
}

pub(crate) fn decode_expr_if(term: Term) -> NifResult<Expr> {
    let condition = super::decode_expr(term.map_get(super::atom(term.get_env(), "condition")?)?)?;
    let then_block = super::decode_block(term.map_get(super::atom(term.get_env(), "then")?)?)?;
    let else_block = super::decode_block(term.map_get(super::atom(term.get_env(), "else")?)?)?;
    super::parse_expr_tokens(quote!(if # condition # then_block else # else_block))
}

pub(crate) fn decode_expr_tuple(term: Term) -> NifResult<Expr> {
    let values = super::decode_expr_list(term.map_get(super::atom(term.get_env(), "values")?)?)?;
    super::parse_expr_tokens(quote!((# (# values),*)))
}
